server:
  port: 8080
logging:
  level:
    ru.podgoretskaya: DEBUG

spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/guide
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: 'update'
