server:
  port: 8080
logging:
  level:
    ru.podgoretskaya: DEBUG

#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/guide
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: 'update'
